# Workflow for building and deploying a Next.js site to Vercel
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to Vercel

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # Build and deploy job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

    #   - name: Install dependencies
    #     run: npm ci

      - name: Create .env file
        run: |
          cat << EOF > .env
          
          RESEND_API_KEY = ${{ secrets.RESEND_API_KEY }}
          EMAIL_FROM = ${{ secrets.EMAIL_FROM }}
          NOTIFICATION_EMAIL = ${{ secrets.NOTIFICATION_EMAIL }}
          NEXT_PUBLIC_BLOG_PASSWORD= ${{ secrets.NEXT_PUBLIC_BLOG_PASSWORD }}
          NEXT_PUBLIC_API_URL= ${{ vars.NEXT_PUBLIC_API_URL }}

          # CLIENT
          NEXT_PUBLIC_API_URL=https://www.showon.ai
          
          EOF

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }} --name=landing-showonai --yes